parameters:
 europaSearch.logger.class: Psr\Log\NullLogger
services:
  # Index item deletion service converter class.
  europaSearch.messageProxy.indexing.delete.item:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Index\DeleteIndexItemConverter
  # WebContent Indexing service converter classes.
  europaSearch.messageProxy.indexing.webContent:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Index\IndexWebContentConverter
  europaSearch.messageProxy.indexing.file:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Index\IndexFileConverter
  europaSearch.componentProxy.metadata.boolean:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\DocumentMetadata\DefaultMetadataConverter
  europaSearch.componentProxy.metadata.date:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\DocumentMetadata\DateMetadataConverter
  europaSearch.componentProxy.metadata.numeric:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\DocumentMetadata\DefaultMetadataConverter
  europaSearch.componentProxy.metadata.notIndexed:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\DocumentMetadata\DefaultMetadataConverter
  europaSearch.componentProxy.metadata.string:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\DocumentMetadata\DefaultMetadataConverter

  # Search Service converter classes.
  europaSearch.messageProxy.searching.search:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Search\SearchConverter
  europaSearch.componentProxy.searching.filters.clauses.fieldExists:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Clauses\FieldExistsClauseConverter
  europaSearch.componentProxy.searching.filters.clauses.range:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Clauses\RangeClauseConverter
  europaSearch.componentProxy.searching.filters.clauses.term:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Clauses\TermClauseConverter
  europaSearch.componentProxy.searching.filters.clauses.terms:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Clauses\TermsClauseConverter
  europaSearch.componentProxy.searching.filters.queries.aggregate:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Queries\FilterQueryComponentConverter
  europaSearch.componentProxy.searching.filters.queries.booleanQuery:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Queries\BooleanQueryConverter
  europaSearch.componentProxy.searching.filters.queries.boostingQuery:
      class: OpenEuropa\EuropaSearch\Proxies\Converters\Components\Filters\Queries\BoostingQueryConverter

  # Default Layer classes.
  europaSearch.validator.default:
      class: OpenEuropa\EuropaSearch\Messages\DefaultValidatorBuilder
  europaSearch.logger:
      class: %europaSearch.logger.class%
  europasearch.loggerManager:
      class: OpenEuropa\EuropaSearch\Services\LogsManager
      arguments: ['@europaSearch.logger', 'error']
      tags:
        - { name: europasearch.client_logger }
  europaSearch.transporter.default:
      class: OpenEuropa\EuropaSearch\Transporters\EuropaSearchTransporter
      arguments: ['@europaSearch.loggerManager']
  europaSearch.proxyController.default:
      class:  OpenEuropa\EuropaSearch\Proxies\ProxyController
      arguments: ['@europaSearch.loggerManager']
      calls:
          - [setContainer, ['@service_container']]
  europaSearch.application.default:
      class: OpenEuropa\EuropaSearch\Applications\Application
      arguments: ['@europaSearch.validator.default', '@europaSearch.proxyController.default', '@europaSearch.transporter.default', '@europaSearch.loggerManager']